package com.example.Application.enums;

public enum AlertType {
    VISITOR_AT_GATE,
    VISITOR_AT_RECEPTION,
    VISITOR_EN_ROUTE,
    VISITOR_AT_MEETING_ROOM,
    RESTRICTED_ZONE_ALERT,
    TIMEOUT_ALERT,
    EMERGENCY,
    HOST_CONFIRMATION_REQUIRED,
    MEETING_EXTENDED,
    MEETING_TERMINATED,
    VISITOR_CHECKED_OUT
}
